sudo: required

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- docker pull mathlab/deal2lkit:8.5.pre.4-debugrelease
- ./scripts/dr.sh "cd WaveBEM; ./scripts/check_indentation.sh"

script:
- ./scripts/dr.sh "mkdir WaveBEM/build-travis; cd WaveBEM/build-travis; cmake -GNinja -DENABLE_DOCUMENTATION=OFF -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../; ninja"
- ./scripts/dr.sh "cd WaveBEM/build-travis; ctest"
