sudo: required

env:
  - BUILD_TYPE=release
  - BUILD_TYPE=debug

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- docker pull heltai/deal2lkit:$BUILD_TYPE
- docker run -P -v `pwd`:/home/dealii/WaveBEM:rw heltai/deal2lkit:$BUILD_TYPE /bin/sh -c "cd WaveBEM; ./scripts/check_indentation.sh"

script:
- docker run -P -v `pwd`:/home/dealii/WaveBEM:rw heltai/deal2lkit:$BUILD_TYPE /bin/sh -c "mkdir WaveBEM/build; cd WaveBEM/build; cmake -GNinja -DENABLE_DOCUMENTATION=OFF ../; ninja"
- docker run -P -v `pwd`:/home/dealii/WaveBEM:rw heltai/deal2lkit:$BUILD_TYPE /bin/sh -c "cd WaveBEM/build; ctest"
